//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication25 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplication25.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _10578062653902c7414fa39_44004507 {
            get {
                object obj = ResourceManager.GetObject("_10578062653902c7414fa39_44004507", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1406407026_close_square_black {
            get {
                object obj = ResourceManager.GetObject("_1406407026_close_square_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _2048 {
            get {
                object obj = ResourceManager.GetObject("_2048", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] a {
            get {
                object obj = ResourceManager.GetObject("a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Actions_arrow_left_icon {
            get {
                object obj = ResourceManager.GetObject("Actions_arrow_left_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Aero_WinFlip_3D {
            get {
                object obj = ResourceManager.GetObject("Aero_WinFlip_3D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Apps_Adobe_Acrobat_Reader_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Apps_Adobe_Acrobat_Reader_Metro_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Apps_App_Store_alt_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Apps_App_Store_alt_Metro_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Apps_Windows_Media_Player_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Apps_Windows_Media_Player_Metro_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] b {
            get {
                object obj = ResourceManager.GetObject("b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bookmarks {
            get {
                object obj = ResourceManager.GetObject("Bookmarks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] c {
            get {
                object obj = ResourceManager.GetObject("c", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Calendar {
            get {
                object obj = ResourceManager.GetObject("Calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap chalkboard_background_full_page {
            get {
                object obj = ResourceManager.GetObject("chalkboard_background_full_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clock_alarm_icon {
            get {
                object obj = ResourceManager.GetObject("clock_alarm_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Clock_icon {
            get {
                object obj = ResourceManager.GetObject("Clock_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ClockFace {
            get {
                object obj = ResourceManager.GetObject("ClockFace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CodeGen {
            get {
                object obj = ResourceManager.GetObject("CodeGen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Coding_app {
            get {
                object obj = ResourceManager.GetObject("Coding_app", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 1
        ///5 9
        ///6 3
        ///2 3
        ///7 8
        ///15 15
        ///20 12
        ///22 13
        ///4 2
        ///12 2
        ///1 1
        ///4 5
        ///9 0
        ///0 9
        ///1 4
        ///5 12
        ///1 4
        ///8 15
        ///15 8
        ///20 3
        ///32 2
        ///14 4
        ///8 7
        ///17 5
        ///18 9
        ///19 12
        ///3 6
        ///25 16
        ///28 12
        ///15 10
        ///10 10
        ///14 12
        ///4 19
        ///60 15
        ///45 12
        ///55 15
        ///42 0
        ///7 8
        ///23 12
        ///12 10
        ///28 2
        ///0 0.
        /// </summary>
        public static string coord {
            get {
                return ResourceManager.GetString("coord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] d {
            get {
                object obj = ResourceManager.GetObject("d", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone + Tablet
        ///PHABLET
        ///Most Populus Country
        ///CHINA
        ///The Space Lab
        ///ISS
        ///First Indian Woman In Space
        ///KALPANA CHAWLA
        ///First Indian In Space
        ///RAKESH SHARMA
        ///Where You Walk To Avoid Traffic?
        ///PAVEMENT
        ///A Portable Switch Box
        ///EXTENSION BOX
        ///A Natural Satellite to Earth
        ///MOON
        ///The Lead Role Of Beyblade
        ///TYSON
        ///The Bit Beast Of Tyson
        ///DRAGOON
        ///The Most Beautiful Language
        ///TAMIL
        ///Most Cleanest Country
        ///SWISS
        ///Founder Of Facebook
        ///MARK ZUGGERBURG
        ///Crystal Used In Clocks
        ///QUARTZ
        ///The Country Where Talent is Poache [rest of string was truncated]&quot;;.
        /// </summary>
        public static string data1 {
            get {
                return ResourceManager.GetString("data1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Location Tech Device
        ///WI FI
        ///A Laptop Brand Under Sony
        ///VAIO
        ///Other Name Of NewsPapers
        ///DAILY
        ///A 1980 * 1080 Screen
        ///FULL HD SCREEN
        ///The Most Popular Website In The World
        ///GOOGLE
        ///The Recent Innovation By Apple
        ///FINGERPRINT LOCK
        ///The Most Famous Deal Of This Decade
        ///WHATSAPP FACEBOOK DEAL
        ///Overlooks the Stock Markets In India
        ///SEBI
        ///The Costliest And Desired Watch Brand
        ///ROLEX
        ///The Most Protective Glass In Mobiles
        ///GORILLA GLASS
        ///The Indian Mobile Market Player
        ///MICROMAX
        ///Which Country Did MH370 Belo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string data2 {
            get {
                return ResourceManager.GetString("data2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between India And Srilanka
        ///PALK STRAIT
        ///Portable Phones
        ///MOBILE
        ///We Are In A Galaxy Called
        ///MILKY WAY GALAXY
        ///Harvested Facts
        ///DATA
        ///Processed Data
        ///INFORMATION
        ///A Group Of Shops Under Same Roof
        ///MALL
        ///Mode To Turn Off Wireless Connections
        ///AIRPLANE
        ///The Most Abundant Elemnent In the Universe
        ///HYDROGEN
        ///The Techno Used In Modern Batteries
        ///LITHIUM ION
        ///Radiation Absorber
        ///BLACK BODY
        ///Hindu God - Protector
        ///VISHNU
        ///Tells u r late
        ///WATCHES
        ///Microsoft CEO
        ///NADELLA
        ///Leaving Microsoft CEO
        ///STEVE BALLMER
        ///Most P [rest of string was truncated]&quot;;.
        /// </summary>
        public static string data3 {
            get {
                return ResourceManager.GetString("data3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving Microsoft CEO
        ///STEVE BALLMER
        ///Most Popular o/s
        ///MICROSOFT WINDOWS
        ///What Is The Tile Interface Called?
        ///METRO INTERFACE
        ///Attracts Iron
        ///MAGNET
        ///Most Cleanest Country
        ///SWISS
        ///Founder Of Facebook
        ///MARK ZUGGERBURG
        ///Crystal Used In Clocks
        ///QUARTZ
        ///The Country Where Talent is Poached From?
        ///INDIA
        ///A Well Known Spares Manufacturer Of Apple
        ///SAMSUNG
        ///The Famous Detective Serial
        ///SHERLOCK HOLMES
        ///When You Try Sell An Idea?
        ///PRESENTATION
        ///The Most Famous Software Repository
        ///FILEHIPPO
        ///Founder Of Facebook
        ///MA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string data4 {
            get {
                return ResourceManager.GetString("data4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Are In A Galaxy Called
        ///MILKY WAY GALAXY
        ///Harvested Facts
        ///DATA
        ///Processed Data
        ///INFORMATION
        ///A Group Of Shops Under Same Roof
        ///MALL
        ///Mode To Turn Off Wireless Connections
        ///AIRPLANE
        ///The Most Abundant Elemnent In the Universe
        ///HYDROGEN
        ///The Techno Used In Modern Batteries
        ///LITHIUM ION
        ///Radiation Absorber
        ///BLACK BODY
        ///Hindu God - Protector
        ///VISHNU
        ///Tells u r late
        ///WATCHES
        ///Microsoft CEO
        ///NADELLA
        ///Leaving Microsoft CEO
        ///STEVE BALLMER
        ///Most Popular o/s
        ///MICROSOFT WINDOWS
        ///What Is The Tile Interface Called?        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string data5 {
            get {
                return ResourceManager.GetString("data5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digg_alt {
            get {
                object obj = ResourceManager.GetObject("digg_alt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Drives_Computer_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Drives_Computer_Metro_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] e {
            get {
                object obj = ResourceManager.GetObject("e", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] errormsg {
            get {
                object obj = ResourceManager.GetObject("errormsg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Explorer {
            get {
                object obj = ResourceManager.GetObject("Explorer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] f {
            get {
                object obj = ResourceManager.GetObject("f", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] file_history {
            get {
                object obj = ResourceManager.GetObject("file_history", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5	1.
        /// </summary>
        public static string file_selector {
            get {
                return ResourceManager.GetString("file_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FileHistory {
            get {
                object obj = ResourceManager.GetObject("FileHistory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] first_open {
            get {
                object obj = ResourceManager.GetObject("first_open", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Flappy_Smiley {
            get {
                object obj = ResourceManager.GetObject("Flappy_Smiley", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Folders_OS_My_Videos_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Folders_OS_My_Videos_Metro_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Folders_OS_Recycle_Bin_Full_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Folders_OS_Recycle_Bin_Full_Metro_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] g {
            get {
                object obj = ResourceManager.GetObject("g", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap google {
            get {
                object obj = ResourceManager.GetObject("google", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Google_Maps {
            get {
                object obj = ResourceManager.GetObject("Google_Maps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] h {
            get {
                object obj = ResourceManager.GetObject("h", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Hang_Man {
            get {
                object obj = ResourceManager.GetObject("Hang_Man", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Hang_Man_Source {
            get {
                object obj = ResourceManager.GetObject("Hang_Man_Source", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] history_data_provider {
            get {
                object obj = ResourceManager.GetObject("history_data_provider", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Hour {
            get {
                object obj = ResourceManager.GetObject("Hour", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] i {
            get {
                object obj = ResourceManager.GetObject("i", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imagesCA4YNB9H {
            get {
                object obj = ResourceManager.GetObject("imagesCA4YNB9H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] j {
            get {
                object obj = ResourceManager.GetObject("j", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] JUMPER {
            get {
                object obj = ResourceManager.GetObject("JUMPER", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] k {
            get {
                object obj = ResourceManager.GetObject("k", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap k7921468 {
            get {
                object obj = ResourceManager.GetObject("k7921468", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] kappspot_notes {
            get {
                object obj = ResourceManager.GetObject("kappspot_notes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] l {
            get {
                object obj = ResourceManager.GetObject("l", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Light_Wood_Background_Wallpaper_1024x640 {
            get {
                object obj = ResourceManager.GetObject("Light_Wood_Background_Wallpaper_1024x640", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///-----------------------------------------------------------------------
        ///|   PLAYER 1 | SCORE |   PLAYER 2 | SCORE | TURNS |   GAME STATISTICS |
        ///-----------------------------------------------------------------------.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] m {
            get {
                object obj = ResourceManager.GetObject("m", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Minute {
            get {
                object obj = ResourceManager.GetObject("Minute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Music {
            get {
                object obj = ResourceManager.GetObject("Music", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] n {
            get {
                object obj = ResourceManager.GetObject("n", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] o {
            get {
                object obj = ResourceManager.GetObject("o", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Other_Mail_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Other_Mail_Metro_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Other_Search_alt_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Other_Search_alt_Metro_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Other_Search_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Other_Search_Metro_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] p {
            get {
                object obj = ResourceManager.GetObject("p", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap paint {
            get {
                object obj = ResourceManager.GetObject("paint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Paint1 {
            get {
                object obj = ResourceManager.GetObject("Paint1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Pin {
            get {
                object obj = ResourceManager.GetObject("Pin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Power___Switch_User {
            get {
                object obj = ResourceManager.GetObject("Power___Switch_User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] q {
            get {
                object obj = ResourceManager.GetObject("q", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] r {
            get {
                object obj = ResourceManager.GetObject("r", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Recycle_Bin_Empty_alt {
            get {
                object obj = ResourceManager.GetObject("Recycle_Bin_Empty_alt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Reddit {
            get {
                object obj = ResourceManager.GetObject("Reddit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] s {
            get {
                object obj = ResourceManager.GetObject("s", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SearchHistory {
            get {
                object obj = ResourceManager.GetObject("SearchHistory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Second {
            get {
                object obj = ResourceManager.GetObject("Second", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Share {
            get {
                object obj = ResourceManager.GetObject("Share", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] shooting {
            get {
                object obj = ResourceManager.GetObject("shooting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Start_Menu_Search_icon {
            get {
                object obj = ResourceManager.GetObject("Start_Menu_Search_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] t {
            get {
                object obj = ResourceManager.GetObject("t", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] u {
            get {
                object obj = ResourceManager.GetObject("u", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] v {
            get {
                object obj = ResourceManager.GetObject("v", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] w {
            get {
                object obj = ResourceManager.GetObject("w", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Web_Browsers_Internet_Explorer_10_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Web_Browsers_Internet_Explorer_10_Metro_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Web_Facebook_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Web_Facebook_Metro_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Web_icon {
            get {
                object obj = ResourceManager.GetObject("Web_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Web_Wikipedia_alt_2_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Web_Wikipedia_alt_2_Metro_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Web_Windows_Store_Metro_icon {
            get {
                object obj = ResourceManager.GetObject("Web_Windows_Store_Metro_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap windjview_metro_style_icon_by_rangewanderer_d5yqw24_png {
            get {
                object obj = ResourceManager.GetObject("windjview_metro_style_icon_by_rangewanderer_d5yqw24_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap windows8_people_128x128 {
            get {
                object obj = ResourceManager.GetObject("windows8_people_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] wordament {
            get {
                object obj = ResourceManager.GetObject("wordament", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wordament1 {
            get {
                object obj = ResourceManager.GetObject("wordament1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] x {
            get {
                object obj = ResourceManager.GetObject("x", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] y {
            get {
                object obj = ResourceManager.GetObject("y", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] z {
            get {
                object obj = ResourceManager.GetObject("z", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
